name: Release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build
    - name: Archive build results
      run: tar -czhf "${{ github.ref_name }}.tar.gz" -C result .
    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ github.ref_name }}.tar.gz
